#!/usr/bin/env bash
#This script displays to 4-to_infinity_and_beyond indefinitely
#+ a sleep 2 in between each iteration
# Displays "I am invincible!!!" in between each iteration

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
