#!/usr/bin/env bash
#Change localhost to 127.0.0.2
#Change facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.cpy
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.cpy
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.cpy
cp -f ~/hosts.cpy /etc/hosts
